# Generated by Django 4.1.5 on 2023-04-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лікар'), (2, 'Пацієнт')], default=1),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField(verbose_name='Спеціалізація')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата прийому')),
                ('time', models.TimeField(verbose_name='Час прийому')),
                ('complains', models.TextField(verbose_name='Причини звернення')),
                ('symptoms', models.TextField(verbose_name='Симптоматика')),
                ('diagnosys', models.TextField(verbose_name='Діагноз')),
                ('recomendations', models.TextField(verbose_name='Рекомендації')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.doctor', verbose_name='Лікар')),
                ('patietn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Прийом',
                'verbose_name_plural': 'Прийоми',
            },
        ),
    ]
