# Generated by Django 4.1.5 on 2023-04-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_role_doctor_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosys',
            field=models.TextField(blank=True, null=True, verbose_name='Діагноз'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recomendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Симптоматика'),
        ),
    ]
