# Generated by Django 4.1.5 on 2023-04-18 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('reception', models.BooleanField(verbose_name='Рецептурний препарат')),
            ],
            options={
                'verbose_name': 'Ліки',
                'verbose_name_plural': 'Ліки',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.medical', verbose_name='Ліки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник')),
            ],
        ),
    ]
